In [39]:
import numpy as np
from numpy import genfromtxt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import confusion_matrix, classification_report

https://archive.ics.uci.edu/dataset/267/banknote+authentication

In [3]:
data = genfromtxt('../resources/data/bank_note_data.txt', delimiter=',')

In [4]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]],
      shape=(1372, 5))

In [7]:
etiquetas = data[:,4]
etiquetas

array([0., 0., 0., ..., 1., 1., 1.], shape=(1372,))

In [8]:
caracteristicas = data[:,0:4]
caracteristicas

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]], shape=(1372, 4))

In [9]:
X = caracteristicas
y = etiquetas

## Sepramos los datos en train y test

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [13]:
len(X_train)

919

In [14]:
len(X)

1372

In [15]:
len(X_test)

453

In [16]:
len(y_train)

919

In [17]:
len(y_test)

453

### Normalizar los datos

In [19]:
scaler_object = MinMaxScaler()

In [20]:
scaler_object.fit(X_train)

MinMaxScaler()

In [21]:
scaled_X_train = scaler_object.transform(X_train)

In [23]:
scaled_X_train.max()

np.float64(1.0000000000000002)

In [24]:
scaled_X_test = scaler_object.transform(X_test)

In [26]:
scaled_X_test.max()

np.float64(1.02679563427227)

## Construimos el modelo

In [29]:
model = Sequential()
model.add(Dense(4, input_dim = 4, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

/home/brayan/anaconda3/envs/ComputerVision/lib/python3.13/site-packages/keras/src/layers/core/dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2025-11-11 13:17:23.341634: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [30]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

## Entrenamos el Modelo

In [32]:
model.fit(scaled_X_train, y_train, epochs=100, verbose=2)

Epoch 1/100
29/29 - 0s - 3ms/step - accuracy: 0.9260 - loss: 0.2289
Epoch 2/100
29/29 - 0s - 3ms/step - accuracy: 0.9369 - loss: 0.2216
Epoch 3/100
29/29 - 0s - 3ms/step - accuracy: 0.9402 - loss: 0.2137
Epoch 4/100
29/29 - 0s - 3ms/step - accuracy: 0.9369 - loss: 0.2080
Epoch 5/100
29/29 - 0s - 4ms/step - accuracy: 0.9391 - loss: 0.2011
Epoch 6/100
29/29 - 0s - 3ms/step - accuracy: 0.9423 - loss: 0.1955
Epoch 7/100
29/29 - 0s - 4ms/step - accuracy: 0.9423 - loss: 0.1890
Epoch 8/100
29/29 - 0s - 7ms/step - accuracy: 0.9478 - loss: 0.1830
Epoch 9/100
29/29 - 0s - 6ms/step - accuracy: 0.9445 - loss: 0.1780
Epoch 10/100
29/29 - 0s - 5ms/step - accuracy: 0.9478 - loss: 0.1725
Epoch 11/100
29/29 - 0s - 5ms/step - accuracy: 0.9510 - loss: 0.1676
Epoch 12/100
29/29 - 0s - 7ms/step - accuracy: 0.9532 - loss: 0.1624
Epoch 13/100
29/29 - 0s - 5ms/step - accuracy: 0.9532 - loss: 0.1577
Epoch 14/100
29/29 - 0s - 5ms/step - accuracy: 0.9499 - loss: 0.1537
Epoch 15/100
29/29 - 0s - 5ms/step - accura

In [34]:
predictions = model.predict(scaled_X_test)

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 


In [35]:
classes = (predictions > 0.5).astype(int)

In [36]:
classes

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    

## Evaluamos los resultados

In [37]:
model.metrics_names

['loss', 'compile_metrics']

In [38]:
model.evaluate(x = scaled_X_test, y = y_test)

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9801 - loss: 0.0432  


[0.04321805015206337, 0.9801324605941772]

In [40]:
confusion_matrix(y_test, classes)

array([[250,   7],
       [  2, 194]])

In [41]:
print(classification_report(y_test, classes))

              precision    recall  f1-score   support

         0.0       0.99      0.97      0.98       257
         1.0       0.97      0.99      0.98       196

    accuracy                           0.98       453
   macro avg       0.98      0.98      0.98       453
weighted avg       0.98      0.98      0.98       453



## Guardar el modelo

In [42]:
model.save('mi_modelo.h5')

### Utilizar nuestro modelo

In [43]:
from keras.models import load_model

In [44]:
nuevo_modelo = load_model('mi_modelo.h5')

In [45]:
nuevo_modelo.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 8)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 71 (288.00 B)

 Trainable params: 69 (276.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2 (12.00 B)